/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ClinicaLista;

import ClinicaLista.controller.ClinicController;
import ClinicaLista.dao.ClinicDAO;
import ClinicaLista.database.Conexao;
import ClinicaLista.view.ClinicView;
import java.sql.Connection;

public class App {
    public static void main(String[] args) {
        // Conectar ao banco e criar a tabela
        Connection conn = Conexao.conectar();
        Conexao.criarTabela();

        // Criar o DAO e o Controller
        ClinicDAO clinicDAO = new ClinicDAO(conn);
        ClinicController clinicController = new ClinicController(clinicDAO);

        // Passar o controller para o view
        new ClinicView(clinicController).setVisible(true);
     
    }
}
